apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pathnex-nginx
  namespace: argocd  # Argo CD lives in this namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/pathnex/ArgoCd_lab.git'  # Your Git repo with Helm chart
    targetRevision: HEAD  # Track the latest commit
    path: .               # Path to your Helm chart inside the repo
    helm:
      valueFiles:
        - values.yaml    # Your Helm values file
  destination:
    server: 'https://kubernetes.default.svc'  # Cluster API
    namespace: pathnex                        # Deploy nginx here
  syncPolicy:
    automated:
      prune: true     # Remove resources deleted from Git
      selfHeal: true  # Auto-heal if live cluster drifts from Git